config/routes.rb
Rails.application.routes.draw do
  resources :groups, only: [:index, :show]
  resources :participants, only: [:create]

  root 'site#index'
end

app/models/participant.rb
class Participant < ActiveRecord::Base

  validates :email, uniqueness: true, presence: true
  validates :name, :group_id, presence: true

  def self.by_group(group_id)
    where(group_id: group_id)
  end

  def self.taken
    where(taken: true)
  end

  def self.available
    where(taken: false)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    redirect_to group_path(params[:id])
  end

  def show
    @participant = Participant.new(group_id: params[:id])
    @playing = Participant.by_group(params[:id])
  end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController

  def create
    @participant = Participant.new(participant_params)
    if @participant.save
      redirect_to root_path, notice: 'YAY! Good luck'
    else
      redirect_to group_path(participant_params[:group_id]), alert: "Oops. You're already signed up."
    end
  end

  private

  def participant_params
    params.require(:participant).permit(:group_id, :name, :email)
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def cdnjs_tag(project)
    javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/#{project}"
  end

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = :success if type.to_s == 'notice'
      type = :danger  if type.to_s == 'alert'
      text = content_tag(:div, link_to(content_tag(:i, '', class: "icon-remove-sign alert-#{type}"), "#", class: 'close', data: {dismiss: 'alert'}) + message, class: "alert fade in alert-#{type}")
      flash_messages << text if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/views/groups/_pre_game.html.erb
<h1 class="title text-center">Game Starts in</h1>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="clock" data-end-date="20141210"></div>
  </div>
</div>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <p class="lead text-center">Sign up to play! We will email you your secret recipient.</p>
    <%= form_for(@participant) do |f| %>
    <%= f.hidden_field(:group_id) %>
    <div class="row">
      <div class="col-sm-6">
        <%= f.text_field(:name, class: 'form-control input-lg', placeholder: 'Your Name') %>
      </div>
      <div class="col-sm-6">
        <%= f.email_field(:email, class: 'form-control input-lg', placeholder: 'Your Email') %>
      </div>
    </div>
    <br />
    <%= f.submit('Join the fun!', class: 'btn btn-lg btn-success btn-block') %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<% if Game.pregame? %>
  <%= render('pre_game') %>
<% else %>
  <h1 class="title text-center">Game On!</h1>
  <p class="lead text-center">Go buy a gift, and make it fun!</p>
<% end %>
<div class="row stat-box">
  <div class="col-sm-8 col-sm-offset-2">
    There <%= "is".pluralize(@playing.count) %> <span class="accent"><%= pluralize(@playing.count, 'person') %></span> playing. So far there are <span class="accent"><%= @playing.taken.count %></span> secret santas. Your group ID is <span class="accent"><%= params[:id] %></span>. 
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-us">
<head>
  <title>SecretSanta</title>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta name="mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag('application', media: 'all') %>
  <%= cdnjs_tag('modernizr/2.8.2/modernizr.min.js') %>
  <!--[if lt IE 9]>
    <%= cdnjs_tag('html5shiv/3.6.1/html5shiv.js') %>
    <%= cdnjs_tag('respond.js/1.4.2/respond.js') %>
  <![endif]-->
</head>
<body>
  <div class="container">
    <%= bootstrap_flash %>
    <%= yield %>
  </div>
  <footer class="footer">
    <p class="text-center">Made with <i class="fa fa-heart"></i> by <a href="http://twitter.com/jeremywoertink" target="_blank">@jeremywoertink</a></p>
  </footer>
  <%= javascript_include_tag('application') %>
</body>
</html>

app/views/site/index.html.erb
<h1 class="title text-center">Secret Santa</h1>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_tag(groups_path, method: :get) do %>
      <div class="input-group input-group-lg" id="group-id-form">
        <%= text_field_tag(:id, '', class: 'form-control', placeholder: 'Which group are you with?') %>
        <span class="input-group-btn">
          <button type="submit" class="btn btn-success btn-lg">
            <i class="fa fa-tree"></i>
          </button>
        </span>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-sm-12 text-center">
    <small>Merry Christmas!</small>
  </div>
</div>